### ISSUE TITLE
Sequence base_type attribute not supported for sequence<octet>"

### ISSUE THREAD

**Issue by PaulRousse** [Sdpierret/pyopendds#19]
https://github.com/Sdpierret/pyopendds/blob/3def6e01b145022c8adae1316a874809bc8b29c3/pyopendds/dev/itl2py/PythonOutput.py#L115

the base_type attribute of generated pyopendds objects is equal to None for objects of types sequence<octet>.
It should be of type UByte or Byte.

**Comment by Sdpierret** [comment]
will it be solved by #27  ?
